fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    'common':
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.0.2'
  symlinks:
    facter: "#{source_dir}"
