fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v9.0.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: 'v7.1.1'
