name    'ghoneycutt-facter'
version '1.3.1'
source 'git://github.com/ghoneycutt/puppet-module-facter.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage Facter'
description 'Manage Facter and optionally ensure facts.d directory.'
project_page 'https://github.com/ghoneycutt/puppet-module-facter'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
